FROM davidsantia/fs-node

ADD gameday/list.js_v0.5 /src/assets/list.js
ADD gameday/list.handlebars_v0.5 /src/views/list.handlebars
ADD gameday/navbar.handlebars_v0.5 /src/views/partials/navbar.handlebars
